name: Draft a Release
on:
  workflow_dispatch:
    inputs:
      tagName:
        description: 'Tag Name'
        default: ''
        type: string
        required: true
          
env:
  tagName: ${{ github.event.inputs.tagName }}

jobs:
    slackNotification:
        name: Draft a Release
        runs-on: ubuntu-latest
        steps:
             - uses: actions/checkout@v3
               with:
                  ref: 'main'
                  
             - name: Create Tag
               run: |
                 git config user.name github-actions
                 git config user.email github-actions@github.com
                 git tag -a ${{ env.tagName }} -m "version ${{ env.tagName }}"
                 git push --tags
                 
             - name: Get current date
               id: date
               run: echo "::set-output name=date::$(date +'%d-%m-%Y')"
               
             - name: Create release
               uses: ncipollo/release-action@v1.10.0
               id: 'create-release'
               with:
                  tag: ${{ env.tagName }}
                  generateReleaseNotes: true
                  draft: true

             
                 
            
