name: Push Release Slack Notificaion
on:
    release:
        types: [published]

jobs:
    slackNotification:
        name: Slack Notification
        runs-on: ubuntu-latest
        steps:
            - name: Get current date
              id: date
              run: echo "::set-output name=date::$(date +'%d-%m-%Y')"

            - name: Slack Markdown Converter
              uses: LoveToKnow/slackify-markdown-action@v1.0.0
              id: slackBody
              with:
                  text: ${{ github.event.release.body }}
            - name: Slack notification
              env:
                  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
                  SLACK_USERNAME: Github Release Bot
                  SLACK_CHANNEL: release-note-private
                  SLACK_AVATAR: https://raw.githubusercontent.com/whoami-shubham/release-notes-slack/main/github.png
              uses: Ilshidur/action-slack@2.0.2
              with:
                  args: "*App Name ${{ github.event.release.name }} RELEASE - ${{ steps.date.outputs.date }}* \n\n RelaseLink: ${{github.event.release.html_url}} \n\n ${{ steps.slackBody.outputs.text }} \n\n\n\n"
